const campuses = [
//	{ "id": 56, "name": "Prague" },
//	{ "id": 55, "name": "Tétouan" },
//	{ "id": 54, "name": "42-test" },
//	{ "id": 53, "name": "Vienna" },
//	{ "id": 52, "name": "Florence" },
//	{ "id": 51, "name": "Berlin" },
//	{ "id": 50, "name": "Kocaeli" },
//	{ "id": 49, "name": "Istanbul" },
//	{ "id": 48, "name": "Mulhouse" },
//	{ "id": 47, "name": "Lausanne" },
//	{ "id": 46, "name": "Barcelona" },
//	{ "id": 45, "name": "Alicante" },
//	{ "id": 44, "name": "Wolfsburg" },
//	{ "id": 43, "name": "Abu Dhabi" },
//	{ "id": 42, "name": "42Network" },
//	{ "id": 41, "name": "Nice" },
//	{ "id": 40, "name": "Urduliz" },
//	{ "id": 39, "name": "Heilbronn" },
//	{ "id": 38, "name": "Lisboa" },
//	{ "id": 37, "name": "Malaga" },
//	{ "id": 36, "name": "Adelaide" },
//	{ "id": 35, "name": "Amman" },
//	{ "id": 34, "name": "Kuala Lumpur" },
//	{ "id": 33, "name": "Bangkok" },
//	{ "id": 32, "name": "Yerevan" },
//	{ "id": 31, "name": "Angouleme" },
//	{ "id": 30, "name": "Rome" },
//	{ "id": 29, "name": "Seoul" },
//	{ "id": 28, "name": "Rio de Janeiro" },
//	{ "id": 27, "name": "Hack High School - Fremont " },
//	{ "id": 26, "name": "Tokyo" },
//	{ "id": 25, "name": "Quebec" },
//	{ "id": 24, "name": "Novosibirsk" },
//	{ "id": 23, "name": "Kazan" },
//	{ "id": 22, "name": "Madrid" },
//	{ "id": 21, "name": "Benguerir" },
//	{ "id": 20, "name": "São-Paulo" },
//	{ "id": 19, "name": "CoderDojoSV" },
//	{ "id": 18, "name": "iTouchUP" },
//	{ "id": 17, "name": "Moscow" },
//	{ "id": 16, "name": "Khouribga" },
//	{ "id": 15, "name": "Cape-Town" },
//	{ "id": 14, "name": "Amsterdam" },
//	{ "id": 13, "name": "Helsinki" },
//	{ "id": 12, "name": "Brussels" },
//	{ "id": 11, "name": "Montrouge" },
//	{ "id": 10, "name": "Bucharest" },
//	{ "id": 9, "name": "Lyon" },
//	{ "id": 8, "name": "Kyiv" },
//	{ "id": 7, "name": "Fremont" },
//	{ "id": 6, "name": "Chisinau" },
//	{ "id": 5, "name": "Johannesburg" },
//	{ "id": 2, "name": "Cluj" },
	{ "id": 1, "name": "Paris" }
];

module.exports = campuses;
